name: FbModal
author: chris nizzardini, kj ye
category: Widgets
tags: [window, modal, overlay, popup]
demo: http://www.cnizz.com/mootools/fb-modal/
docs: http://blog.cnizz.com/tag/fbmodal/
current: 0.9.3
